### ISSUE TITLE
Fazer testes com o novo server de e-mails (node)

### ISSUE THREAD

**Issue by dbarjs** [elbitdigital/elbit#3]
- [x] fazer teste com nodemailer (https://www.npmjs.com/package/nodemailer)
- [x] fazer teste de rotas usando o express (https://www.npmjs.com/package/express)
- [x] criar server now (http://now.sh/)
- [x] fazer aplicação teste de envio de e-mail
- [x] fazer deploy do serviço no now
- [x] testar HTTP

**Comment by dbarjs** [comment]
@cristianofromagio ping

**Comment by cristianofromagio** [comment]
@dbarjs pong

**Comment by cristianofromagio** [comment]
Rodado e testado https://github.com/elbitdigital/node-server
